// <auto-generated />
namespace solo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-preview5-19254-05")]
    public sealed partial class actualizeall4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(actualizeall4));
        
        string IMigrationMetadata.Id
        {
            get { return "201906121507362_actualizeall4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
